table customer_master
	lineageTag: b267e4cd-5966-4d8b-b747-0ae34d576863

	column customer_id
		dataType: string
		lineageTag: 5e7be19d-fbf1-4191-ad71-af3ce6905e93
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: bba6c8b5-8c67-486f-bcc3-d8ae49c7ab99
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column customer_age
		dataType: int64
		formatString: 0
		lineageTag: bde7a9c3-b268-4366-b15e-4229541fdd15
		summarizeBy: none
		sourceColumn: customer_age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 31d103a9-d22c-4f20-8d3c-01ad8ccb410e
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column customer_segment
		dataType: string
		lineageTag: 4542c9f1-1bf6-4b6e-8135-c36ed8fc47bd
		summarizeBy: none
		sourceColumn: customer_segment

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 4c3ada58-86fc-4427-b60a-8c0aa1970dfc
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 537277c1-503f-4b17-a91c-74526b11794c
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: a12e806e-a943-4eef-9104-d2207cfb21dd
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 03959dcf-c694-4a5d-bd5f-5807822ed98b
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column customer_postal_code
		dataType: string
		lineageTag: 96eb328d-ecba-4605-868b-906683e30fb9
		summarizeBy: none
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

	column customer_acquisition_cost
		dataType: double
		lineageTag: bd768206-2d1d-4f88-a2c6-1351790388f3
		summarizeBy: none
		sourceColumn: customer_acquisition_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Age Range' =
			
			SWITCH(
			    TRUE(),
			    'customer_master'[customer_age] < 20, "< 20",
			    'customer_master'[customer_age] >= 20 && 'customer_master'[customer_age] <= 29, "20-29",
			    'customer_master'[customer_age] >= 30 && 'customer_master'[customer_age] <= 39, "30-39",
			    'customer_master'[customer_age] >= 40 && 'customer_master'[customer_age] <= 49, "40-49",
			    'customer_master'[customer_age] >= 50 && 'customer_master'[customer_age] <= 59, "50-59",
			    "60+"
			)
		lineageTag: 5089cd68-ea17-47f8-856c-9f59abe93ec0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition customer_master = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Marty\Documents\Kaggle Datasets\E-Commerce Sales\customer_master.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_name", type text}, {"customer_age", Int64.Type}, {"gender", type text}, {"customer_segment", type text}, {"customer_city", type text}, {"customer_state", type text}, {"customer_country", type text}, {"region", type text}, {"customer_postal_code", Int64.Type}, {"customer_acquisition_cost", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"customer_postal_code", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

