table order_items
	lineageTag: 2965bff0-45d4-47c5-916a-1eb0611567d2

	column order_id
		dataType: string
		lineageTag: ebd5c6d4-7830-4a16-bcbe-c56a64a59558
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: a3bc8d43-5d49-4393-b3c6-4df7aba88279
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: #,0
		lineageTag: 7abd11c7-a9a9-45d8-ba2a-7158d6e3e263
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: 8d0e48d5-28d2-4f14-bd47-603fa5dc259d
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discount_percentage
		dataType: double
		lineageTag: 9ff4275c-6bcd-4851-b719-57f31bc4aa94
		summarizeBy: sum
		sourceColumn: discount_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discount_amount
		dataType: double
		lineageTag: d02bca2c-8bda-4d78-a671-6c7e7ccf8369
		summarizeBy: sum
		sourceColumn: discount_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gross_sales
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8b01a8a5-aff9-40c7-acb2-f94562410560
		summarizeBy: sum
		sourceColumn: gross_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column tax_amount
		dataType: double
		lineageTag: 00155d97-0a36-4d38-9d6a-33454748c2ab
		summarizeBy: sum
		sourceColumn: tax_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shipping_cost
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f27b2bdc-f351-457b-a093-4b7346f24516
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column net_sales
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7ca3d5f0-f1d6-48c2-9813-7aa85be17cdb
		summarizeBy: sum
		sourceColumn: net_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column product_cost
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 31c83c5e-7a3d-4293-8e8a-f5e65b3dc4fd
		summarizeBy: sum
		sourceColumn: product_cost

		annotation SummarizationSetBy = Automatic

	column profit
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0a0456e8-41ff-4dcc-afcf-794d3d984764
		summarizeBy: sum
		sourceColumn: profit

		annotation SummarizationSetBy = Automatic

	partition order_items = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Marty\Documents\Kaggle Datasets\E-Commerce Sales\order_items.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"product_id", type text}, {"quantity", Int64.Type}, {"unit_price", type number}, {"discount_percentage", type number}, {"discount_amount", type number}, {"gross_sales", type number}, {"tax_amount", type number}, {"shipping_cost", type number}, {"net_sales", type number}, {"product_cost", type number}, {"profit", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"discount_percentage", Percentage.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

