table product_catalog
	lineageTag: 7bd46992-cba7-4673-91b7-8d5fabbfffaa

	column product_id
		dataType: string
		lineageTag: e71314ea-c057-411b-b6f5-5f7516f856cf
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 7101ea21-6389-48b6-a52c-126998c2806c
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: b15fcb4a-c4f3-4576-8b5d-daed4c2912f2
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column product_subcategory
		dataType: string
		lineageTag: d5e0789b-281e-4b74-a5e3-7819f2280788
		summarizeBy: none
		sourceColumn: product_subcategory

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: 2e25eaee-4c82-43e0-9297-f43314c6147a
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: 6d0ac3d1-17c3-4a89-9120-ee5097ab7fbb
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: a39491c8-4cb2-4f21-8269-162fd7262bd1
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_cost
		dataType: double
		lineageTag: ef5d6572-45f7-4b5b-a8cf-a6925b25aca8
		summarizeBy: none
		sourceColumn: product_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_rating
		dataType: double
		lineageTag: 92fb9f49-1439-440d-b9a9-db733b26c9d9
		summarizeBy: none
		sourceColumn: product_rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition product_catalog = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Marty\Documents\Kaggle Datasets\E-Commerce Sales\product_catalog.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", type text}, {"product_name", type text}, {"product_category", type text}, {"product_subcategory", type text}, {"brand", type text}, {"supplier", type text}, {"unit_price", type number}, {"product_cost", type number}, {"product_rating", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

